package docs

import "embed"

// SwaggerJSON embeds swagger.json so the ReDoc route (internal/routes) can
// serve it via redoc.Redoc's SpecFS option instead of a bare OS file path.
// A bare relative path resolves against the process's current working
// directory, which differs between `go test` (the package's own directory)
// and a production/container invocation (the deploy root) — embedding
// removes that dependency entirely. Hand-written, not generated by
// `swag init`; kept in its own file so regenerating docs.go never touches
// it.
//
//go:embed swagger.json
var SwaggerJSON embed.FS
